In [1]:
import numpy as np

In [5]:
lst = [1,3,4,5,6,7,8,9]
arr = np.array(lst)
arr

array([1, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# A matrix has different vectors or lists grouped one on top of the other, it is like an Excel table
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#the first position is the first row
matriz[0]

array([1, 2, 3])

In [8]:
# To select a single element of the array, specify the position of the element separated by commas.
# Note: The first element selects the rows, the second element the columns
matriz[0,2]

3

＊＊＊＊＊＊＊＊＊　SLICING　＊＊＊＊＊＊＊＊＊

In [10]:
# It allows us to extract various data, it has a beginning and an end.
# In this example we are extracting data from position 1 to 5.
arr[1:6]

array([3, 4, 5, 6, 7])

In [9]:
arr[1:6]

array([3, 4, 5, 6, 7])

In [12]:
#To know how many dimentions are
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [13]:
# ＊＊＊＊＊＊＊＊＊DECLARE A VECTOR
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [14]:
# ＊＊＊＊＊＊＊＊＊DECLARE A MATRIX
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [15]:
# ＊＊＊＊＊＊＊＊＊DECLARE A TENSOR
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


3

In [16]:
# Add dimentions 
# Agregar o eliminar dimensiones
# Se puede definir el número de dimensiones desde la declaración del array

vector = np.array([1, 2, 3], ndmin = 10)
print(vector) 
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [17]:
#Se pueden expandir dimensiones a los array ya existentes con expand_dims(). Axis = 0 hace referencia a las filas, mientras que axis = 1 a las columnas.

expand = np.expand_dims(np.array([1, 2, 3]), axis = 0)
print(expand)
expand.ndim 

[[1 2 3]]


2

In [18]:
#Remover/comprimir las dimensiones que no están siendo usadas.

print(vector, vector.ndim) 
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
